[[redirects]]
  from = "/partner"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/factory"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/internal"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/pie_defect.html"
  to = "/pie_defect.html"
  status = 200

[[redirects]]
  from = "/data.json"
  to = "/data.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
